/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mvc.view;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mvc.controller.Persistence_Geral;
import mvc.dao.TesteDao;
import mvc.model.Teste;

/**
 *
 * @author Again
 */
public class appFrame extends javax.swing.JFrame
{
    private final Persistence_Geral persistence_Geral = new Persistence_Geral();
    private final TesteDao testeDao = new TesteDao(persistence_Geral.getEntityManagerFactory());
    
    private Teste teste_E = new Teste();
    private Image image;
    private String caminhoImagem = null;
    private File arquivo;
    /**
     * Creates new form appFrame
     */
    public appFrame()
    {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTabbedPane_Principal = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblMensagem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtSobreNome = new javax.swing.JTextField();
        txtIdade = new javax.swing.JTextField();
        txtImg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jlbImg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNome1_E = new javax.swing.JTextField();
        txtSobreNome_E = new javax.swing.JTextField();
        jlbImg_E = new javax.swing.JLabel();
        txtIdade_E = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtImg_E = new javax.swing.JTextField();
        jbtEditar_E = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jtfCodigoPesq_E = new javax.swing.JTextField();
        jbtPesq_E = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jlbMsg_E = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jcbCritPesq_R = new javax.swing.JComboBox();
        txtPesq_R = new javax.swing.JTextField();
        jbtPesq_R = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesquisar_R = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtPesq_P = new javax.swing.JTextField();
        jbtPesq_P = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePesquisar_P = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jcbCritPesq_P = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableListar_L = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane_Principal.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jTabbedPane_PrincipalStateChanged(evt);
            }
        });
        jTabbedPane_Principal.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jTabbedPane_PrincipalMouseClicked(evt);
            }
        });
        jTabbedPane_Principal.addInputMethodListener(new java.awt.event.InputMethodListener()
        {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt)
            {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt)
            {
                jTabbedPane_PrincipalCaretPositionChanged(evt);
            }
        });
        jTabbedPane_Principal.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jTabbedPane_PrincipalPropertyChange(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_home.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jTabbedPane_Principal.addTab("Home", jPanel6);

        jPanel1.setEnabled(false);

        lblMensagem.setText("#Mensagem");

        jLabel1.setText("Nome:");

        jLabel2.setText("SobreNome: ");

        jLabel3.setText("idade:");

        jLabel4.setText("img:");

        txtNome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNomeActionPerformed(evt);
            }
        });

        txtSobreNome.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSobreNomeActionPerformed(evt);
            }
        });

        txtIdade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIdadeActionPerformed(evt);
            }
        });

        txtImg.setEnabled(false);
        txtImg.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtImgActionPerformed(evt);
            }
        });

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        jlbImg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Choose img");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMensagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(60, 60, 60)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtSobreNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jlbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(lblMensagem))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        jTabbedPane_Principal.addTab("Cadastrar", jPanel1);

        jLabel6.setText("Nome:");

        jLabel7.setText("SobreNome: ");

        jLabel8.setText("idade:");

        jLabel9.setText("img:");

        txtNome1_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNome1_EActionPerformed(evt);
            }
        });

        txtSobreNome_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtSobreNome_EActionPerformed(evt);
            }
        });

        jlbImg_E.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtIdade_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtIdade_EActionPerformed(evt);
            }
        });

        jButton3.setText("Choose img");
        jButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton3ActionPerformed(evt);
            }
        });

        txtImg_E.setEnabled(false);
        txtImg_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtImg_EActionPerformed(evt);
            }
        });

        jbtEditar_E.setText("Editar");
        jbtEditar_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtEditar_EActionPerformed(evt);
            }
        });

        jLabel10.setText("Codigo");

        jbtPesq_E.setText("Pesq");
        jbtPesq_E.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtPesq_EActionPerformed(evt);
            }
        });

        jlbMsg_E.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtImg_E, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(57, 57, 57)
                                .addComponent(txtNome1_E, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(60, 60, 60)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdade_E, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSobreNome_E, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtEditar_E)
                        .addGap(37, 37, 37)
                        .addComponent(jlbMsg_E, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbImg_E, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfCodigoPesq_E, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtPesq_E)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfCodigoPesq_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesq_E))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNome1_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtSobreNome_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIdade_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtImg_E, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtEditar_E)
                            .addComponent(jlbMsg_E, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlbImg_E, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        jTabbedPane_Principal.addTab("Editar", jPanel2);

        jLabel5.setText("Criterio Pesquisa");

        jcbCritPesq_R.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nome", "Sobre Nome", "Idade" }));

        jbtPesq_R.setText("Pesq");
        jbtPesq_R.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtPesq_RActionPerformed(evt);
            }
        });

        tablePesquisar_R.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Codigo", "Nome", "Sobre Nome", "Idade"
            }
        ));
        jScrollPane1.setViewportView(tablePesquisar_R);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCritPesq_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesq_R, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtPesq_R))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcbCritPesq_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesq_R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesq_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane_Principal.addTab("Remover", jPanel3);

        jbtPesq_P.setText("Pesq");
        jbtPesq_P.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbtPesq_PActionPerformed(evt);
            }
        });

        tablePesquisar_P.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Codigo", "Nome", "Sobre Nome", "Idade"
            }
        ));
        jScrollPane3.setViewportView(tablePesquisar_P);

        jLabel11.setText("Criterio Pesquisa");

        jcbCritPesq_P.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nome", "Sobre Nome", "Idade" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCritPesq_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesq_P, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtPesq_P))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcbCritPesq_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesq_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtPesq_P))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane_Principal.addTab("Pesquisar", jPanel4);

        tableListar_L.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Codigo", "Nome", "Sobre Nome", "Idade"
            }
        ));
        tableListar_L.addHierarchyListener(new java.awt.event.HierarchyListener()
        {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt)
            {
                tableListar_LHierarchyChanged(evt);
            }
        });
        jScrollPane5.setViewportView(tableListar_L);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane_Principal.addTab("Listar", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNomeActionPerformed
    {//GEN-HEADEREND:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtSobreNomeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSobreNomeActionPerformed
    {//GEN-HEADEREND:event_txtSobreNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobreNomeActionPerformed

    private void txtIdadeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIdadeActionPerformed
    {//GEN-HEADEREND:event_txtIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeActionPerformed

    private void txtImgActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtImgActionPerformed
    {//GEN-HEADEREND:event_txtImgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Teste teste = new  Teste();
        
        teste.setIdteste(0);
        teste.setNome(txtNome.getText().trim());
        teste.setSobreNome(txtSobreNome.getText().trim());
        teste.setIdade(txtIdade.getText().trim());
        teste.setImg(gravarImagemBd());
        
        testeDao.create(teste);
        limparDados();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNome1_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNome1_EActionPerformed
    {//GEN-HEADEREND:event_txtNome1_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1_EActionPerformed

    private void txtSobreNome_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtSobreNome_EActionPerformed
    {//GEN-HEADEREND:event_txtSobreNome_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobreNome_EActionPerformed

    private void txtIdade_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtIdade_EActionPerformed
    {//GEN-HEADEREND:event_txtIdade_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdade_EActionPerformed

    private void txtImg_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtImg_EActionPerformed
    {//GEN-HEADEREND:event_txtImg_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImg_EActionPerformed

    private void jbtEditar_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtEditar_EActionPerformed
    {//GEN-HEADEREND:event_jbtEditar_EActionPerformed
        teste_E.setNome(txtNome1_E.getText().trim() );
        teste_E.setSobreNome(txtSobreNome_E.getText().trim() );
        teste_E.setIdade(txtIdade_E.getText().trim() );
        teste_E.setImg(gravarImagemBd() );
        
        try
        {
            testeDao.edit(teste_E);
        }
        catch (Exception ex)
        {
            Logger.getLogger(appFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparDados();
    }//GEN-LAST:event_jbtEditar_EActionPerformed

    private void jbtPesq_EActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtPesq_EActionPerformed
    {//GEN-HEADEREND:event_jbtPesq_EActionPerformed
      limparDados();
       teste_E = testeDao.findTeste(Integer.parseInt(jtfCodigoPesq_E.getText().trim()) );
       priencherFormEditarComDados(teste_E);
       
       if(teste_E.getImg()!=null)
       lerImagemBd(teste_E);
       
    }//GEN-LAST:event_jbtPesq_EActionPerformed

    private void jTabbedPane_PrincipalMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jTabbedPane_PrincipalMouseClicked
    {//GEN-HEADEREND:event_jTabbedPane_PrincipalMouseClicked
        // TODO add your handling code here:
        // Evento do Click do anel Listar
        
    }//GEN-LAST:event_jTabbedPane_PrincipalMouseClicked

    private void tableListar_LHierarchyChanged(java.awt.event.HierarchyEvent evt)//GEN-FIRST:event_tableListar_LHierarchyChanged
    {//GEN-HEADEREND:event_tableListar_LHierarchyChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableListar_LHierarchyChanged

    private void jTabbedPane_PrincipalPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jTabbedPane_PrincipalPropertyChange
    {//GEN-HEADEREND:event_jTabbedPane_PrincipalPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane_PrincipalPropertyChange

    private void jTabbedPane_PrincipalCaretPositionChanged(java.awt.event.InputMethodEvent evt)//GEN-FIRST:event_jTabbedPane_PrincipalCaretPositionChanged
    {//GEN-HEADEREND:event_jTabbedPane_PrincipalCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane_PrincipalCaretPositionChanged

    private void jTabbedPane_PrincipalStateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_jTabbedPane_PrincipalStateChanged
    {//GEN-HEADEREND:event_jTabbedPane_PrincipalStateChanged
        // TODO add your handling code here:
        if(jTabbedPane_Principal.getSelectedIndex() == 4){
            priencherTableListar();
        }
    }//GEN-LAST:event_jTabbedPane_PrincipalStateChanged

    private void jbtPesq_PActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtPesq_PActionPerformed
    {//GEN-HEADEREND:event_jbtPesq_PActionPerformed
        // TODO add your handling code here:
        priencherTablePesquisar();
    }//GEN-LAST:event_jbtPesq_PActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        escolherImagem(jlbImg);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        // TODO add your handling code here:
        escolherImagem(jlbImg_E);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbtPesq_RActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbtPesq_RActionPerformed
    {//GEN-HEADEREND:event_jbtPesq_RActionPerformed
        // Remove a Teste
        priencherTableRemove();
        
    }//GEN-LAST:event_jbtPesq_RActionPerformed

    
    
    public void priencherTableListar(){
        
        tableListar_L.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableListar_L.getColumnModel().getColumn(1).setPreferredWidth(150 );
        tableListar_L.getColumnModel().getColumn(2).setPreferredWidth(150 );
        tableListar_L.getColumnModel().getColumn(3).setPreferredWidth(20 );
        
        DefaultTableModel modelo = (DefaultTableModel)tableListar_L.getModel();
        modelo.setNumRows(0);
        
        for (Teste teste : testeDao.findTesteEntities())
        {
            modelo.addRow(new Object []{
                teste.getIdteste(),
                teste.getNome(),
                teste.getSobreNome(),
                teste.getIdade()
            });
        } 
    }
    
    public List<Teste> SearchTeste_P(){         
        return testeDao.findAny(jcbCritPesq_P.getSelectedIndex(), txtPesq_P.getText().trim());
    }
    
    public List<Teste> SearchTeste_R(){         
        return testeDao.findAny(jcbCritPesq_R.getSelectedIndex(), txtPesq_R.getText().trim());
    }
    
    public void priencherTablePesquisar(){
        
        //List<Teste> listaTestePesquisa = testeDao.pesquisarVarios(opcao, idTeste, nome, sobreNome, idade);
        
        tablePesquisar_P.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablePesquisar_P.getColumnModel().getColumn(1).setPreferredWidth(150 );
        tablePesquisar_P.getColumnModel().getColumn(2).setPreferredWidth(150 );
        tablePesquisar_P.getColumnModel().getColumn(3).setPreferredWidth(20 );
        
        DefaultTableModel modelo = (DefaultTableModel)tablePesquisar_P.getModel();
        modelo.setNumRows(0);
         
        
        for (Teste teste : SearchTeste_P())
        {
            modelo.addRow(new Object[]{
                teste.getIdteste(),
                teste.getNome(),
                teste.getSobreNome(),
                teste.getIdade()
            });
        }
    }
    
    public void priencherTableRemove(){
        
        //List<Teste> listaTestePesquisa = testeDao.pesquisarVarios(opcao, idTeste, nome, sobreNome, idade);
        
        tablePesquisar_R.getColumnModel().getColumn(0).setPreferredWidth(50);
        tablePesquisar_R.getColumnModel().getColumn(1).setPreferredWidth(150 );
        tablePesquisar_R.getColumnModel().getColumn(2).setPreferredWidth(150 );
        tablePesquisar_R.getColumnModel().getColumn(3).setPreferredWidth(20 );
        
        DefaultTableModel modelo = (DefaultTableModel)tablePesquisar_R.getModel();
        modelo.setNumRows(0);
         
        
        for (Teste teste : SearchTeste_R())
        {
            modelo.addRow(new Object[]{
                teste.getIdteste(),
                teste.getNome(),
                teste.getSobreNome(),
                teste.getIdade()
            });
        }
    }
    
    
    
    public void limparDados(){
        txtIdade.setText("");
        txtNome.setText("");
        txtSobreNome.setText("");
        txtImg.setText("");
        
        txtIdade_E.setText("");
        txtNome1_E.setText("");
        txtSobreNome_E.setText("");
        txtImg_E.setText("");
        
    }
    
    public void priencherFormEditarComDados(Teste teste){
        if(teste!=null){
            txtNome1_E.setText(""+teste.getNome());
            txtSobreNome_E.setText(""+teste.getSobreNome());
            txtIdade_E.setText(""+teste.getIdade());
            txtImg_E.setText(""+teste.getImg());
        }else jlbMsg_E.setText("Nao Encotrado!!!");
    }
    
    public byte[] gravarImagemBd(){
        try{
            BufferedImage bImage = ImageIO.read(arquivo);
            
            //OBTEM A IMAGEM E TRANSFORMA EM BYTES[]  
            ByteArrayOutputStream bytesImg = new ByteArrayOutputStream();  
            ImageIO.write(bImage, "jpg", bytesImg);//seta a imagem para bytesImg  \
            
            
            bytesImg.flush();//limpa a variável  
            byte[] byteArray = bytesImg.toByteArray();//Converte ByteArrayOutputStream para byte[]   
            //bytesImg.close();//fecha a conversão  
              
            return byteArray;
            
        }catch(IOException ex){
            System.out.println("Retornando Null..............");
            return null;
        }
    }
    
    public void lerImagemBd(Teste teste){
        byte[] foto = null;  
          
        //LENDO E COPIANDO IMAGEM ##############################################  
        BufferedImage img = null;   
        //reg = regDao.findById(7);  
                                  
        try {  
            img = ImageIO.read(new ByteArrayInputStream(teste.getImg()));
            
            ImageIcon imageIcon_E = new ImageIcon(img);
            imageIcon_E.setImage(imageIcon_E.getImage().getScaledInstance(jlbImg_E.getWidth(), jlbImg_E.getHeight(), 100));
            jlbImg_E.setIcon(imageIcon_E);      
            ImageIO.write(img, "jpg", new File("foto.jpg"));
          
        } catch (IOException e) {  
            // TODO Auto-generated catch block  
            e.printStackTrace();  
        }  
    }
    
    public void escolherImagem(JLabel lblImgMostrar){
               JFileChooser fileChooser = new JFileChooser();
               
                int res = fileChooser.showOpenDialog(null);

                if(res == JFileChooser.APPROVE_OPTION){
                    arquivo = fileChooser.getSelectedFile();
                    JOptionPane.showMessageDialog(null, "Voce escolheu o arquivo: " + arquivo.getAbsolutePath());
                    txtImg.setText(""+fileChooser.getSelectedFile().getAbsolutePath() );
                    
                    caminhoImagem = ""+fileChooser.getSelectedFile().getAbsolutePath();
                    
                    ImageIcon imageIcon = new ImageIcon(fileChooser.getSelectedFile().getAbsolutePath());
                    imageIcon.setImage(imageIcon.getImage().getScaledInstance(lblImgMostrar.getWidth(), lblImgMostrar.getHeight(), 100));
                    
                    //Image img = imageIcon.getImage();
                    image = imageIcon.getImage();
                    
                    lblImgMostrar.setIcon(imageIcon);
                    
                    JOptionPane.showMessageDialog(null, "Voce escolheu o arquivo: " + fileChooser.getSelectedFile().getAbsolutePath() );
                }
                else
                    JOptionPane.showMessageDialog(null, "Voce nao selecionou nenhum arquivo."); 
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane_Principal;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbtEditar_E;
    private javax.swing.JButton jbtPesq_E;
    private javax.swing.JButton jbtPesq_P;
    private javax.swing.JButton jbtPesq_R;
    private javax.swing.JComboBox jcbCritPesq_P;
    private javax.swing.JComboBox jcbCritPesq_R;
    private javax.swing.JLabel jlbImg;
    private javax.swing.JLabel jlbImg_E;
    private javax.swing.JLabel jlbMsg_E;
    private javax.swing.JTextField jtfCodigoPesq_E;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JTable tableListar_L;
    private javax.swing.JTable tablePesquisar_P;
    private javax.swing.JTable tablePesquisar_R;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtIdade_E;
    private javax.swing.JTextField txtImg;
    private javax.swing.JTextField txtImg_E;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1_E;
    private javax.swing.JTextField txtPesq_P;
    private javax.swing.JTextField txtPesq_R;
    private javax.swing.JTextField txtSobreNome;
    private javax.swing.JTextField txtSobreNome_E;
    // End of variables declaration//GEN-END:variables
}
